set(BEAST_BOYS_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Streamer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Streamer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Messenger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Messenger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Common/WebsocketTypes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Common/WebsocketResponse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Common/WebsocketResponse.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/WebsocketImpl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/WebsocketImpl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/RawMessenger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/RawMessenger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/RawStreamer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/RawStreamer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Common/RawSocketResponse.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Common/RawSocketResponse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Common/RawSocketTypes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawConnector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawConnector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawReceiver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawReceiver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawResolver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawResolver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSender.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSender.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSharedState.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSharedState.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSocketImpl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSocketImpl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawStream.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawStream.cpp

    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/Client.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/Client.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/Doorman.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/Doorman.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/RawConnection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/RawConnection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/Server.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/Server.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/ServerState.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketServer/ServerState.cpp


    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/SharedState.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/SharedState.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/Logger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/CryptoHelper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/CryptoHelper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/Json.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/Json.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Resolver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Resolver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Stream.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Stream.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Connector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Connector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/SSLHandShaker.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/SSLHandShaker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/TargetHandShaker.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/TargetHandShaker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Receiver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Receiver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Sender.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl/Sender.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/RestApi.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/NetworkRequestSettings.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/NetworkRequestSettings.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/NetworkTypes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/RestApiResponse.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/RestApiResponse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl/BoostInternalImpl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl/BoostInternalImpl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl/ResponseHelper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl/ResponseHelper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/RespApi.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/beastboys
)

set(BEAST_BOYS_FOLDERS
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/external
    ${CMAKE_CURRENT_SOURCE_DIR}/external/rapidjson/include
    ${CMAKE_CURRENT_SOURCE_DIR}/fmt/include
    ${CMAKE_CURRENT_SOURCE_DIR}/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/SocketApi/Impl
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl
)
