set(BEAST_BOYS_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/cacert_data.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Resolver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Resolver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Stream.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Stream.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Connector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Connector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/SSLHandShaker.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/SSLHandShaker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/TargetHandShaker.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/TargetHandShaker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Receiver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Receiver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Sender.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/Sender.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/WebsocketImpl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/WebsocketImpl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/SharedState.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl/SharedState.h

    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Streamer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Streamer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Messenger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Messenger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Common/WebsocketTypes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Common/WebsocketResponse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Common/WebsocketResponse.h

    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/RawMessenger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/RawMessenger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/RawStreamer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/RawStreamer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Common/RawSocketResponse.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Common/RawSocketResponse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Common/RawSocketTypes.h

    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawConnector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawConnector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawReceiver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawReceiver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawResolver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawResolver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSender.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSender.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSharedState.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSharedState.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSocketImpl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawSocketImpl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawStream.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl/RawStream.cpp

    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/Client.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/Client.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/Connection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/Connection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/Doorman.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/Doorman.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/Server.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/Server.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/ServerState.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common/ServerState.cpp

    ${CMAKE_CURRENT_SOURCE_DIR}/Server/RawSocketServer/RawDoorman.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/RawSocketServer/RawDoorman.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/RawSocketServer/RSConnection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/RawSocketServer/RSConnection.cpp

    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer/WebSocketDoorman.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer/WebSocketDoorman.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer/HttpListener.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer/HttpListener.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer/HandShaker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer/HandShaker.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer/WSConnection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer/WSConnection.cpp

    ${CMAKE_CURRENT_SOURCE_DIR}/Common/Logger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/CryptoHelper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/CryptoHelper.h

    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/RestApi.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/NetworkRequestSettings.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/NetworkRequestSettings.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/NetworkTypes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/RestApiResponse.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common/RestApiResponse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl/BoostInternalImpl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl/BoostInternalImpl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl/ResponseHelper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl/ResponseHelper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/RespApi.cpp

    ${CMAKE_CURRENT_SOURCE_DIR}/beastboys
)

set(BEAST_BOYS_FOLDERS
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/external
    ${CMAKE_CURRENT_SOURCE_DIR}/external/rapidjson/include
    ${CMAKE_CURRENT_SOURCE_DIR}/fmt/include
    ${CMAKE_CURRENT_SOURCE_DIR}/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/Common/Error
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/WebSocketApi/Impl
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/RestApi/Impl
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/RawSocketServer
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/RawSocketApi/Impl
    ${CMAKE_CURRENT_SOURCE_DIR}/Server
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/Common
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/RawSocketServer
    ${CMAKE_CURRENT_SOURCE_DIR}/Server/WebSocketServer
)
